"""Add description column to Document

Revision ID: ffcda1105e9b
Revises: 69e9e9dc5116
Create Date: 2025-01-10 06:15:50.697288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffcda1105e9b'
down_revision: Union[str, None] = '69e9e9dc5116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'description')
    # ### end Alembic commands ###
